version: "3.8"

services:
  mateonunez_frontend_nextjs:
    container_name: mateonunez_frontend_nextjs
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    working_dir: /usr/src/mateonunez/website
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/mateonunez/website
      - /usr/src/mateonunez/website/node_modules
      - /usr/src/mateonunez/website/.next
    networks:
      - mun_network

networks:
  mun_network:
    driver: bridge
